### ISSUE TITLE
Infinite recursions

### ISSUE THREAD

**Issue by binarykitchen** [STRML/forward-emitter#1]
When I have these code lines in my app

```
        forward(visuals.getRecorder(), controller)
        forward(visuals.getRecorder(), buttons)
        forward(visuals,               buttons)
        forward(controller,            buttons)
```

I see infinite recursions and this error in the latest Google Chrome:

```
eventEmitter.js:16 <error>eventEmitter.js:16 emitevents.js:117 EventEmitter.addListenerindex.js:11 (anonymous function)events.js:80 EventEmitter.emitevents.js:117 EventEmitter.addListenerindex.js:11 (anonymous function)events.js:80 EventEmitter.emiteventEmitter.js:17 emitevents.js:117 EventEmitter.addListenerindex.js:11 (anonymous function)events.js:99 EventEmitter.emiteventEmitter.js:17 emitevents.js:117 EventEmitter.addListenerindex.js:11 (anonymous function)events.js:80 EventEmitter.emitevents.js:117 EventEmitter.addListenerindex.js:11 (anonymous function)events.js:80 EventEmitter.emiteventEmitter.js:17 emit
...
```

**Comment by STRML** [comment]
You are most likely setting up a loop.

You forward `visuals.getRecorder()` to controller, and to buttons, and then controller again to buttons. Perhaps that is why.

The source of this module is very simple, I doubt it is a bug.

**Comment by binarykitchen** [comment]
Hmm, I see. How can I change the code so that the controller is able to receive forwarded events and to emit events forth, in both directions?

**Comment by binarykitchen** [comment]
?

**Comment by cressie176** [comment]
I'm also getting this in the [rascal](https://github.com/guidesmiths/rascal) project, but I think it's forward-emitter that's creating the loop. The problem only occurs when adding the third event source to the same destination. The event that triggers the loop is adding a handler for "removeListener". I'll try to put together a test case.

**Comment by cressie176** [comment]
``` js
  it('should not loop forever', function(done) {
    var src1 = new EventEmitter();
    var src2 = new EventEmitter();
    var src3 = new EventEmitter();
    var dest = new EventEmitter();
    forward(src1, dest);
    forward(src2, dest);
    forward(src3, dest);

    done()
  });
```

Output...

```
 forward(src, dest)
Forwarding all events from EventEmitter undefined to EventEmitter
Adding removeListener to EventEmitter undefined
Forwarding all events from EventEmitter undefined to EventEmitter
Adding newListener to EventEmitter undefined
Adding removeListener to EventEmitter undefined
Adding removeListener to EventEmitter undefined
Adding removeListener to EventEmitter undefined
Forwarding all events from EventEmitter undefined to EventEmitter
Adding newListener to EventEmitter undefined
Adding newListener to EventEmitter undefined
Adding newListener to EventEmitter undefined
Adding newListener to EventEmitter undefined
Adding removeListener to EventEmitter undefined
Adding removeListener to EventEmitter undefined
Adding removeListener to EventEmitter undefined
Adding removeListener to EventEmitter undefined
Adding removeListener to EventEmitter undefined
Adding removeListener to EventEmitter undefined
...
Adding removeListener to EventEmitter undefined
Adding removeListener to EventEmitter undefined
Adding removeListener to EventEmitter undefined
Adding removeListener to EventEmitter undefined
Adding removeListener to EventEmitter undefined
    1) should not loop forever


  0 passing (119ms)
  1 failing

  1) forward(src, dest) should not loop forever:
     RangeError: Maximum call stack size exceeded
      at String.replace (native)
      at exports.format (util.js:27:23)
      at Console.log (console.js:36:34)
      at EventEmitter.<anonymous> (index.js:14:13)
      at EventEmitter.<anonymous> (index.js:15:34)
      at EventEmitter.<anonymous> (index.js:15:34)
```

**Comment by STRML** [comment]
Thanks. That's a bug.

**Comment by cressie176** [comment]
```
forward(src1, dest) // adds a "removeListener" handler to src1
forward(src2, dest) // adds a "removeListener" handler to src1 and src2
forward(src3, dest) // adds a "removeListener" handler to src1 and src2 and src3 (infinitely)
```

**Comment by cressie176** [comment]
Can be worked around by excluding the "removeListener" event via the filter function

**Comment by STRML** [comment]
Thanks @cressie176!

**Comment by cressie176** [comment]
Does this mean that you can't chain forwarded events though?

```
forward(a, b)
forward(b, c)
```

Maybe not. It's making my head spin ;)

**Comment by STRML** [comment]
Let me try. Honestly this was meant to be a very simple module - but I see no reason why it shouldn't support that use case.

**Comment by STRML** [comment]
(Ignore the last comment, haven't seen this code in a while)

See the [test](https://github.com/STRML/forward-emitter/blob/master/test/index.js#L30) for that. :)

**Comment by cressie176** [comment]
Yep - looks good to me (just tried removing listeners in the chain too and the number of calls reduced accordingly)

**Comment by cressie176** [comment]
Thanks very much for your quick response
